### ISSUE TITLE
macOS Clion 无法正常使用

### ISSUE THREAD

**Issue by c1rew** [huoguangjin/MultiHighlight#29]
操作系统：macOS Big Sur Version 11.6.6
IDE：CLion 2022.1.1 Build #CL-221.5591.52, built on May 11, 2022

通过Market下载安装，显示Installed，但是实际没有成功，keymap中无法看到对应选项。
使用文件导入安装，出现以下错误
<img width="548" alt="Screen Shot 2022-05-24 at 10 13 15" src="https://user-images.githubusercontent.com/10029724/169934971-45980ea1-98ad-462e-b0ab-4a2749bbb660.png">

**Comment by huoguangjin** [comment]
老的intellij gradle插件会在打包时指定最高支持的IDE版本（[until-build](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#patchpluginxml-task-untilbuild)）
MultiHighlight 2.2.0的兼容范围是2020.2.3-2021.1.*，所以在CLion 2022.1.1上会被禁用。

解决方法有2个，任选其一：
- 在IDE的插件设置里删掉当前版本的MultiHighlight，重启IDE后再搜索插件然后重新安装。这时候会安装2.1.1版本，它的兼容范围是2020.3+，功能无差别。（但Android Studio 4.2及以上的版本不能通过此方法修复，只能用第二种方法）
- 如果IDE是2020.2.3-2021.3，可以安装[v2.2.1](https://github.com/huoguangjin/MultiHighlight/releases/tag/v2.2.1)；如果IDE是2021.3-2022.*，可以安装[v3.0.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.0.0)。这两个版本都已经在发布审核的流程中了，过两三天就会上架到插件市场，但在还没审核通过前就只能手动安装了。

---

The old intellij gradle plugin will specify the compatibility range for the plugin ([until-build](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#patchpluginxml-task-untilbuild)).
The compatibility range of MultiHighlight 2.2.0 is 2020.2.3-2021.1.*, so you get the error alert on CLion 2022.1.1.

There are 2 solutions, choose either one:
- Uninstall the MultiHighlight in the setting panel, then restart your IDE and install the plugin again. At this time, version 2.1.1 will be installed because its compatibility range is 2020.3+, with no difference in functionality. (but Android Studio 4.2 and above could not use this way, try the second solution below)
- If your IDE is 2020.2.3-2021.3, install [v2.2.1](https://github.com/huoguangjin/MultiHighlight/releases/tag/v2.2.1); If your IDE is 2021.3-2022.*, install [v3.0.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.0.0). These two versions are still under approval and will be released in several days, so you need to install the plugin from disk manually before release.

**Comment by huoguangjin** [comment]
Try [v3.0.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.0.0)
