### ISSUE TITLE
multihighlight doesn't work in c files(clion)

### ISSUE THREAD

**Issue by Florentius** [huoguangjin/MultiHighlight#9]
### 

multihighlight doesn't work in c files(clion)
should I check some preference before this?

it doesn't work at all
please help me

**Comment by huoguangjin** [comment]
- After install this plugin then restart your IDE, it should work.

- I update CLion to `2019.1` today and it work fine:
and it works fine on previous versions (`2018.2` and `2018.3`).
please show me your and CLion version. (check it on menu: `Help > About Clion`)
> CLion 2019.1
Build #CL-191.6183.77, built on March 26, 2019

- I guess the problem is that your shortcut is conflict with other action (or other app),
please check your keymap settings: `File > Settings > Keymap`.
click the magnifier icon and hit the shortcut, make sure that `MultiHighlight: toggle highlight` is shown in the list.

<img width="957" alt="check" src="https://user-images.githubusercontent.com/22366182/56027727-3124c580-5d49-11e9-9346-970acf67664d.png">
